Proceedings reference
isqcmc/isqcmc.github.io pull request #12
Opened 2024-07-22 10:10 UTC by omarcostahamido

2024-07-26 07:42 UTC, Itaborala approved these changes

2024-07-26 07:46 UTC, Itaborala requested changes
Two additional ideas:

- [ ] Should we make a link to the [Zenodo Community](https://zenodo.org/communities/isqcmc_proceedings/) on the top of the page as well?
- [ ] One idea just occured: we make a github release of this repo containing the `Proceedings.md` file. Then we publish this release on Zenodo to obtain a DOI for the proceedings as a whole ....?

2024-10-13 00:24 UTC, omarcostahamido commented
@Itaborala this PR got lost in the woods

> - [ ] Should we make a link to the [Zenodo Community](https://zenodo.org/communities/isqcmc_proceedings/) on the top of the page as well?

Sure

> - [ ] One idea just occured: we make a github release of this repo containing the `Proceedings.md` file. Then we publish this release on Zenodo to obtain a DOI for the proceedings as a whole ....? 

It's a wonky idea but it may work... it is weird because one would cite as proceedings a document where the paper is not readable, but only linked to. I think this project looks much more close to what NIME does. 
edit: actually, just looking at an entry at nime.org it look like they make the references in such a way as if they were part of a book that doesn't seem to exist, they even say in the bib citation the number of pages... interesting. 
Thoughts?

2024-10-13 01:01 UTC, omarcostahamido commented
@Itaborala ready for you to review

2024-10-13 01:43 UTC, omarcostahamido commented
let me know what you think of this last change as well https://github.com/isqcmc/isqcmc.github.io/pull/12/commits/30e2d69d5230ffea33c045fcd07c9c8057a1f0b2

2024-10-16 08:31 UTC, Itaborala commented
> It's a wonky idea but it may work... it is weird because one would cite as proceedings a document where the paper is not readable, but only linked to. I think this project looks much more close to what NIME does. edit: actually, just looking at an entry at nime.org it look like they make the references in such a way as if they were part of a book that doesn't seem to exist, they even say in the bib citation the number of pages... interesting. Thoughts?

Also just looked in the NIME proceedings, and they apparently have a separate Zenodo Community called _Archive_ of the NIME proceedings, where they publish [zip files](https://zenodo.org/records/4016363) with all the papers. Maybe the page ordering comes from there?

I also remember receiving a usb stick as a gift during NIME 2019, which contained all the papers - if my memory is not tricking me - inside a single PDF file.

All in all, I'm not a super fan of using page number in this situation, but I understand they did it also to comply with all citation requirements out there.

An updated suggestion would be to put everything in a zip file and call that the compiled proceedings of ISQCMC Berlin, with a DOI...

2024-10-16 10:46 UTC, omarcostahamido commented
do we need an outsider's opinion to solve this one?

2024-10-16 12:15 UTC, Itaborala commented on Proceedings.md
> +Paper Proceedings for this edition are not available. However, please note that several papers from this edition have evolved into book chapters in:
It does make sense to specify it here, I agree. 

Do you think we should also mention the new book and link it to 2023?

2024-10-16 12:16 UTC, Itaborala commented
> do we need an outsider's opinion to solve this one?

Would be good. I can ask some people here

2024-10-16 16:09 UTC, omarcostahamido commented
@medusamedusa
i know this is not directly about isqcmc2025, but maybe you could give us some suggestion as well?
😇

2024-10-16 16:15 UTC, medusamedusa commented
Sorry, I do not understand :)

Are we going to work on Wordpress, and so I ca share the password, or on GitHub, and so I will ask you how to access and edit it?

BTW, can you please put the logo information before the web design? Thanks :))
Maria


> On 16 Oct 2024, at 18:09, OCH ***@***.***> wrote:
> 
> 
> @medusamedusa <https://github.com/medusamedusa>
> i know this is not directly about isqcmc2025, but maybe you could give us some suggestion as well?
> 😇
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/isqcmc/isqcmc.github.io/pull/12#issuecomment-2417284881>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AXOT4WUIRQHPYP2ZVSNKCXLZ32FVHAVCNFSM6AAAAABLH7WWBKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMJXGI4DIOBYGE>.
> You are receiving this because you were mentioned.
>

2024-10-16 18:08 UTC, medusamedusa commented
I prefer to have a DOI for each article separately.

> * [ ]  One idea just occured: we make a github release of this repo containing the `Proceedings.md` file. Then we publish this release on Zenodo to obtain a DOI for the proceedings as a whole ....?

2024-10-16 18:08 UTC, medusamedusa commented
> @medusamedusa i know this is not directly about isqcmc2025, but maybe you could give us some suggestion as well? 😇

I am now able to read and reply here :)

2024-10-16 18:33 UTC, omarcostahamido commented
@medusamedusa 

> Sorry, I do not understand :)

we are discussing how to create a reference to the entire proceedings of 2023, when we have only published the papers individually on zenodo. Have you been in this situation before? which of the solutions discussed above make sense, or none? It's unrelated to 2025, sorry. but I just thought of asking for an opinion.

> Are we going to work on Wordpress, and so I ca share the password, or on GitHub, and so I will ask you how to access and edit it?

No wordpress please! Just on github. You already have access to https://github.com/isqcmc/isqcmc2025 which is the repo for the 2025 website. you can edit all that you want and propose those changes via Pull request. And you can also open as many issues there as you want to request help to make changes...

> BTW, can you please put the logo information before the web design? Thanks :))

such as this one :D

> I prefer to have a DOI for each article separately.

each article already has its own individual DOI (since late 2023 or early 2024). The question here now is only how to refer to the entire proceedings.

> I am now able to read and reply here :)

Perfect! Yes, it is good to have some context for the messages haha :)

2024-12-20 17:43 UTC, Itaborala approved these changes

2024-12-21 13:14 UTC, merged